[project]
authors = ["TomjWolcott <wolcott.tomj@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "ion-trap-simulation"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
setuptools = ">=73.0.1,<74"
cython = ">=3.0.11,<4"
matplotlib = ">=3.9.2,<4"
cffi = ">=1.17.1,<2"
